/**
 * Agent Zero Bridge — SYNTHIA™ → Agent Zero HTTP adapter
 *
 * Agent Zero runs as a Docker-based orchestrator at AGENT_ZERO_URL (default :8000).
 * It manages subordinate agents with ByteRover (JSON) memory:
 *   ClaudeCode, Synthia, Switchblade, Browser Agent, ML Agent
 *
 * SYNTHIA dispatches execution tasks TO Agent Zero.
 * Agent Zero executes and reports results BACK via /api/council/orchestrator webhook.
 *
 * Security: All calls require AGENT_ZERO_SECRET in Bearer header.
 * Timeout:  AGENT_ZERO_TIMEOUT_MS (default 30s) per request.
 */

import type { SphereAgentId } from '@/shared/council-events';

// ─── Configuration ────────────────────────────────────────────────────────────

const AGENT_ZERO_BASE_URL = process.env.AGENT_ZERO_URL ?? 'http://localhost:8000';
const AGENT_ZERO_SECRET   = process.env.AGENT_ZERO_SECRET ?? '';
const TIMEOUT_MS         = parseInt(process.env.AGENT_ZERO_TIMEOUT_MS ?? '30000', 10);

// ─── Types ────────────────────────────────────────────────────────────────────

export type AgentZeroCapability =
  | 'code'         // ClaudeCode — write / run code
  | 'browser'      // Browser Agent — web automation
  | 'ml'           // ML Agent — data analysis, model inference
  | 'file'         // File system operations
  | 'shell';       // Shell/terminal execution

export interface AgentZeroTask {
  taskId?: string;         // optional pre-assigned ID; generated by Agent Zero if absent
  capability: AgentZeroCapability;
  instruction: string;     // natural language task description
  context?: string;        // any JSON/text context to give the agent
  sphereId?: SphereAgentId; // which sphere delegated this task
  brief_id?: string;       // council brief this task belongs to
  webhookUrl?: string;     // where to POST the result when done
  priority?: 'low' | 'normal' | 'high';
  maxCostUsd?: number;     // per-task budget guard (ZTE: $10 hard cap)
}

export interface AgentZeroStatus {
  taskId: string;
  status: 'queued' | 'running' | 'done' | 'failed' | 'cancelled';
  result?: string;
  error?: string;
  durationMs?: number;
  costUsd?: number;
  agent?: string;          // which sub-agent ran it
}

export interface AgentZeroHealth {
  ok: boolean;
  version?: string;
  queueDepth?: number;
  activeAgents?: string[];
}

export interface AgentRuntimeTopology {
  alexRuntime: 'space-agent';
  subagentRuntime: 'hermes-agent';
  spaceAgentRepo: string;
  hermesAgentRepo: string;
  installationState: 'configured' | 'pending-network-access';
  installationNotes: string;
}

// ─── HTTP helpers ─────────────────────────────────────────────────────────────

function agentZeroHeaders(): HeadersInit {
  const headers: HeadersInit = { 'Content-Type': 'application/json' };
  if (AGENT_ZERO_SECRET) {
    headers['Authorization'] = `Bearer ${AGENT_ZERO_SECRET}`;
  }
  return headers;
}

async function agentZeroFetch<T>(
  path: string,
  init: RequestInit = {},
): Promise<{ data: T; ok: true } | { data: null; ok: false; error: string }> {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), TIMEOUT_MS);

  try {
    const res = await fetch(`${AGENT_ZERO_BASE_URL}${path}`, {
      ...init,
      headers: { ...agentZeroHeaders(), ...(init.headers ?? {}) },
      signal: controller.signal,
    });

    clearTimeout(timer);

    if (!res.ok) {
      const text = await res.text().catch(() => 'no body');
      return { data: null, ok: false, error: `HTTP ${res.status}: ${text}` };
    }

    const json = (await res.json()) as T;
    return { data: json, ok: true };
  } catch (err) {
    clearTimeout(timer);
    return {
      data: null,
      ok: false,
      error: err instanceof Error ? err.message : String(err),
    };
  }
}

// ─── Public API ───────────────────────────────────────────────────────────────

/**
 * Check if Agent Zero is reachable.
 * Returns true even if the service is degraded — caller decides whether to abort.
 */
export async function agentZeroHealthCheck(): Promise<AgentZeroHealth> {
  const result = await agentZeroFetch<{
    status?: string;
    version?: string;
    queue_depth?: number;
    active_agents?: string[];
  }>('/health');

  if (!result.ok) {
    return { ok: false };
  }

  return {
    ok: true,
    version: result.data.version,
    queueDepth: result.data.queue_depth,
    activeAgents: result.data.active_agents,
  };
}

/**
 * Dispatch a task to Agent Zero.
 * Returns the taskId for polling.
 * Enforces $10 per-task cost cap (ZTE circuit breaker).
 */
export async function agentZeroDispatch(task: AgentZeroTask): Promise<string> {
  const safeCost = Math.min(task.maxCostUsd ?? 5, 10); // ZTE: hard $10 cap

  const result = await agentZeroFetch<{ task_id: string }>('/tasks', {
    method: 'POST',
    body: JSON.stringify({
      task_id: task.taskId,
      capability: task.capability,
      instruction: task.instruction,
      context: task.context,
      sphere_id: task.sphereId,
      brief_id: task.brief_id,
      webhook_url: task.webhookUrl,
      priority: task.priority ?? 'normal',
      max_cost_usd: safeCost,
    }),
  });

  if (!result.ok) {
    throw new Error(`[agent-zero-bridge] Dispatch failed: ${result.error}`);
  }

  return result.data.task_id;
}

/**
 * Poll the status of a running task.
 */
export async function agentZeroGetStatus(taskId: string): Promise<AgentZeroStatus> {
  const result = await agentZeroFetch<{
    task_id: string;
    status: AgentZeroStatus['status'];
    result?: string;
    error?: string;
    duration_ms?: number;
    cost_usd?: number;
    agent?: string;
  }>(`/tasks/${encodeURIComponent(taskId)}`);

  if (!result.ok) {
    throw new Error(`[agent-zero-bridge] Status check failed: ${result.error}`);
  }

  return {
    taskId: result.data.task_id,
    status: result.data.status,
    result: result.data.result,
    error: result.data.error,
    durationMs: result.data.duration_ms,
    costUsd: result.data.cost_usd,
    agent: result.data.agent,
  };
}

/**
 * Cancel a running task.
 */
export async function agentZeroCancel(taskId: string): Promise<void> {
  await agentZeroFetch(`/tasks/${encodeURIComponent(taskId)}/cancel`, { method: 'POST' });
}

/**
 * Wait for a task to complete (poll with backoff).
 * Throws if task fails or timeout is exceeded.
 */
export async function agentZeroWaitForResult(
  taskId: string,
  opts: { timeoutMs?: number; pollIntervalMs?: number } = {},
): Promise<AgentZeroStatus> {
  const timeout = opts.timeoutMs ?? 120_000;   // 2 min default
  const interval = opts.pollIntervalMs ?? 2_000;
  const deadline = Date.now() + timeout;

  while (Date.now() < deadline) {
    const status = await agentZeroGetStatus(taskId);

    if (status.status === 'done') return status;
    if (status.status === 'failed') {
      throw new Error(`[agent-zero-bridge] Task ${taskId} failed: ${status.error}`);
    }
    if (status.status === 'cancelled') {
      throw new Error(`[agent-zero-bridge] Task ${taskId} was cancelled`);
    }

    await new Promise(r => setTimeout(r, interval));
  }

  // Timeout — cancel the task
  await agentZeroCancel(taskId).catch(() => {/* best effort */});
  throw new Error(`[agent-zero-bridge] Task ${taskId} timed out after ${timeout}ms`);
}

/**
 * Report a completed Agent Zero result back to SYNTHIA's council orchestrator.
 * This is called by the Agent Zero webhook handler.
 */
export async function reportToSynthia(
  status: AgentZeroStatus,
  sphereId: SphereAgentId,
  brief_id: string,
): Promise<void> {
  const baseUrl = process.env.NEXT_PUBLIC_APP_URL ?? 'http://localhost:3000';
  try {
    await fetch(`${baseUrl}/api/council/orchestrator/agent-result`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ taskId: status.taskId, result: status.result, sphereId, brief_id }),
    });
  } catch (err) {
    console.error('[agent-zero-bridge] Failed to report to SYNTHIA:', err);
    throw err;
  }
}

/**
 * Runtime topology contract for agent orchestration.
 *
 * Requirement:
 * - ALEX runs on top of Space Agent.
 * - All remaining agents are treated as Hermes-backed subagents.
 *
 * Note: this repository environment currently blocks outbound GitHub clone access
 * (HTTP 403 CONNECT tunnel), so installation is tracked as pending until network
 * egress is available in deployment infra.
 */
export function getAgentRuntimeTopology(): AgentRuntimeTopology {
  return {
    alexRuntime: 'space-agent',
    subagentRuntime: 'hermes-agent',
    spaceAgentRepo: 'https://github.com/agent0ai/space-agent',
    hermesAgentRepo: 'https://github.com/NousResearch/hermes-agent',
    installationState: 'pending-network-access',
    installationNotes:
      'GitHub clone currently fails with CONNECT tunnel 403 in this environment; provision in deploy runtime.',
  };
}
